- hosts: localhost
  gather_facts: no

  vars:
    baseuri: "{{ ilo_ip }}"
    username: "{{ ilo_username }}"
    password: "{{ ilo_password }}"

  tasks:
    - name: Insert Virtual Media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        virtual_media:
          image_url: '{{webserver}}/{{bootiso}}'
          media_types:
            - CD
            - DVD
        resource_id: "1"

    - name: SetOneTimeBoot
      vars:
        - bootdevice: "Cd"
      include_role:
        name: hpe.ilo.setonetimeboot

    - name: PowerOn
      include_role:  
        name: hpe.ilo.poweron


