- hosts: localhost
  gather_facts: no

  tasks:

    - name: Get Virtual Media information
      redfish_info:
        category: Manager
        command: GetVirtualMedia
        baseuri: "{{ ilo_ip }}"
        username: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
      register: result_attr

    - name: eject virtual media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaEject
        baseuri: "{{ ilo_ip }}"
        username: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        virtual_media:
          image_url: "{{ item.Image  }}"
          media_types: "{{ item.MediaTypes }}"
        resource_id: "1"
      with_items: "{{result_attr.redfish_facts.virtual_media.entries[0] }}"
      when: item.Image | default(false)

    - name: Insert Virtual Media
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{ ilo_ip }}"
        username: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        virtual_media:
          image_url: '{{webserver}}/{{bootiso}}'
          media_types:
            - CD
            - DVD
        resource_id: "1"

  # tasks file for setonetimeboot
    - name: Set one-time boot device to Cd
      redfish_command:
        category: Systems
        command: SetOneTimeBoot
        bootdevice: "Cd"
        baseuri: "{{ ilo_ip }}"
        username: "{{ ilo_username }}"
        password: "{{ ilo_password }}"

    - name: Insert Virtual Media USB
      community.general.redfish_command:
        category: Manager
        command: VirtualMediaInsert
        baseuri: "{{ ilo_ip }}"
        username: "{{ ilo_username }}"
        password: "{{ ilo_password }}"
        virtual_media:
          image_url: '{{webserver}}/stickks-{{myhostname}}.img'
          media_types:
            - USBStick
        resource_id: "1"


    - name: PowerOn
      vars:
        - baseuri: "{{ ilo_ip }}"
        - username: "{{ ilo_username }}"
        - password: "{{ ilo_password }}"
      include_role:  
        name: hpe.ilo.poweron


