- hosts: localhost
  gather_facts: no
  vars:
    myip: "10.1.70.120"

  tasks:
    - name: wait for port 22 to become active
      wait_for:
        host: "{{myip}}"
        port: 22
        delay: 20
        state: started
        timeout: 1600


    - name: Add ESXi Host to vCenter
      community.vmware.vmware_host:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        datacenter_name: '{{vcdc}}'
        cluster_name: '{{vccluster}}'
        esxi_hostname: '{{ myip }}'
        esxi_username: 'root'
        esxi_password: 'HPE1nvent!'
        state: present
        validate_certs: False
