- hosts: all
  gather_facts: no
  vars:
    - kstemplate: "esx.j2"
    - destination: "ks.cfg"
    - webserverdir: "/var/www/html/iso"

  tasks:
    - name: create custom kickstart file
      template:
        src: "{{kstemplate}}"
        dest:  "{{destination}}"
      delegate_to: localhost


    - name: copy script file
      become: true 
      copy:
        src: "prep_usb.sh"
        dest: /tmp/prep_usb.sh
        owner: root
        group: root
        mode: 0700

    - name: copy script file
      become: true 
      copy:
        src: "usbstick.img"
        dest: /tmp/usbstick.img
        owner: root
        group: root
        mode: 0600

    - name: Ansible Copy Example Local to Remote
      become: true 
      copy:
        src: "{{destination}}"
        dest: /tmp/esx.ks
        owner: apache
        group: apache
        mode: 0666

    - name: prepare usb stick
      become: yes
      shell: "/tmp/prep_usb.sh /tmp {{myhostname}} {{webserverdir}}"

    - set_stats:
        data:
          myip: "{{ myip }}"

