

- hosts: localhost
  gather_facts: no
  vars:
    config: '{{  ovconfig_file }}'
    server_hardware_type_name: " SY480G10 M1:416SA M3:4820CNA"
    enclosure_group_name: "3 Frame VC-ETH SAS-Switch"
    auto_assign_server_hardware: "False"
    ov_template: "ANSIBLE_OS_Deploy_via_iLO"

    - name : "Create Server Profile from Template "
      hpe.oneview.oneview_server_profile:
        config: "{{ config }}"
        data:
          name: "TEST-Ansible"
          serverProfileTemplateName: "{{ ov_template }}"
          serverHardwareName:         "{{ ov_server }}"
        params:
          force: True
      register: mpHostInfo
      delegate_to: localhost
    - debug:
        var:  server_hardware.mpHostInfo.mpIpAddresses[1].address 