- hosts: localhost
  gather_facts: no
  vars:
    - config: '{{  ovconfig_file }}'
    - server_hardware_type_name: "SY 480 Gen11 VC-ETH"
    - enclosure_group_name: "R6 2Frame VC-ETH SAS-Switch"
    - auto_assign_server_hardware: "False"

  tasks:
    - name: "Create Server Profile from Template "
      hpe.oneview.oneview_server_profile:
        config: "{{ config }}"
        data:
          name: "{{ profile_name }}"
          serverProfileTemplateName: "{{ ov_template }}"
          serverHardwareName:         "{{ ov_server }}"
        params:
          force: True
      register: mpHostInfo
      delegate_to: localhost

    - debug:
        var:  server_hardware.mpHostInfo.mpIpAddresses[1].address
    - set_stats:
        data:
          ilo_ip: "{{ server_hardware.mpHostInfo.mpIpAddresses[1].address }}"
